# Generated by Django 2.1.3 on 2018-12-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
        migrations.AddField(
            model_name='shipping',
            name='rec_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to='main.User_Profile'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='send_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to='main.User_Profile'),
        ),
    ]
