# Generated by Django 2.1.3 on 2018-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181203_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='dept_date',
            field=models.DateField(),
        ),
    ]
