# Generated by Django 2.1.3 on 2018-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181204_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('N', 'Not Available'), ('A', 'Available')], default='A', max_length=1),
        ),
    ]
