# Generated by Django 2.1.3 on 2018-12-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_container_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('S', 'Shipped'), ('D', 'Delivered')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='Shipping_Status',
        ),
    ]
